name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Commit SHA
        id: commit
        run: echo "::set-output name=sha_id::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Run a one-line script
        run: |
          echo "Commit ID is ${{ steps.commit.outputs.sha_id }}"
