name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Commit SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
