name: ci

on:
  push:
    branches:
      - 'develop'

jobs:
  job_1:
    name: Build and publish to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vipul8510/workflow-testing:${{ steps.slug.outputs.sha7 }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}