name: CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  docker:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    env:
      commit-id: $(${GITHUB_SHA} | cut -c1-7)
    steps:
      - name: Print Logs
        run:
          echo "commit id is ---------- ${{ env.commit-id }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vipul8510/workflow-testing:${{ env.commit-id }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
