name: Testing Workflows

on:
  push:
    branches: [ main ]

jobs:
  docker:
    name: Print Commands
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "${GITHUB_REF}"
          echo "workflow_testing_{{ github.ref#refs/head/ }}"
